import { Problem } from '../types';
import { formatDate, addDaysToDate } from './spacedRepetition';

export const PRESET_TAGS = [
  'Arrays',
  'Strings',
  'Two Pointers',
  'Sliding Window',
  'Hashing',
  'Linked List',
  'Stack',
  'Queue',
  'Binary Search',
  'Sorting',
  'Recursion',
  'Backtracking',
  'Trees',
  'BST',
  'Heap',
  'Graph',
  'DFS/BFS',
  'Dynamic Programming',
  'Greedy',
  'Bit Manipulation',
  'Math',
  'Trie',
  'Union-Find',
];

const today = formatDate();
const yesterday = addDaysToDate(today, -1);
const twoDaysAgo = addDaysToDate(today, -2);
const threeDaysAgo = addDaysToDate(today, -3);

export const SAMPLE_PROBLEMS: Problem[] = [
  // Overdue problems (for revision queue urgent attention)
  {
    id: 'p-1',
    title: 'Two Sum',
    url: 'https://leetcode.com/problems/two-sum/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Arrays', 'Hashing'],
    notes: '### Approach:\n- Use a HashMap to store `target - num` along with its index.\n- One-pass scan achieves **O(N)** time and **O(N)** space.\n- *Watch out for*: using the same element twice.',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 1,
    next_review_date: yesterday, // Overdue
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'p-2',
    title: 'Detect Cycle in a Directed Graph',
    url: 'https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Graph', 'DFS/BFS'],
    notes: '### Approach:\n- Standard Kahn\'s algorithm (topological sort with in-degree array) or DFS with `vis` and `pathVis` arrays.\n- If count of visited nodes in BFS topological sort != V, there is a cycle!\n- **O(V + E)** time, **O(V)** space.',
    link_verified: true,
    ease_factor: 2.35,
    interval_days: 2,
    repetitions: 2,
    next_review_date: twoDaysAgo, // Overdue
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },

  // Due today problems
  {
    id: 'p-3',
    title: 'Trapping Rain Water',
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    platform: 'leetcode',
    difficulty: 'hard',
    tags: ['Two Pointers', 'Stack', 'Arrays'],
    notes: '### Approach:\n- Two pointers `left = 0, right = n-1`.\n- Track `leftMax` and `rightMax`.\n- Whichever side has smaller max, water trapped is bounded by that max: `ans += leftMax - height[left]`.\n- **O(N)** time, **O(1)** space.',
    link_verified: true,
    ease_factor: 2.4,
    interval_days: 3,
    repetitions: 2,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'p-4',
    title: 'Watermelon',
    url: 'https://codeforces.com/problemset/problem/4/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Math', 'Greedy'],
    notes: '### Logic:\n- If weight `w` is even AND `w > 2`, output YES.\n- `w = 2` splits into 1 and 1 (both odd, so NO).\n- Classic trap: don\'t forget `w == 2` edge case.',
    link_verified: true,
    ease_factor: 2.8,
    interval_days: 5,
    repetitions: 3,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'p-5',
    title: 'Kadane\'s Algorithm',
    url: 'https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Arrays', 'Dynamic Programming'],
    notes: '### Approach:\n- Maximum subarray sum.\n- Keep `currSum = max(num, currSum + num)`.\n- Global max `maxSum = max(maxSum, currSum)`.\n- Handle negative numbers by initializing `maxSum = arr[0]`.',
    link_verified: true,
    ease_factor: 2.65,
    interval_days: 4,
    repetitions: 3,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },

  // Future review / Mastered problems
  {
    id: 'p-6',
    title: 'LRU Cache',
    url: 'https://leetcode.com/problems/lru-cache/',
    platform: 'leetcode',
    difficulty: 'medium',
    tags: ['Linked List', 'Hashing'],
    notes: '### Structure:\n- Doubly Linked List + HashMap mapping key to Node.\n- Dummy head and tail nodes avoid edge cases on node insert/remove.\n- Put adds to MRU (front). Get moves accessed node to front.\n- All operations **O(1)**.',
    link_verified: true,
    ease_factor: 2.8,
    interval_days: 14,
    repetitions: 5, // Mastered!
    next_review_date: addDaysToDate(today, 6),
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'p-7',
    title: 'Way Too Long Words',
    url: 'https://codeforces.com/problemset/problem/71/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Strings'],
    notes: '### Logic:\n- If length > 10, print `firstChar + (len - 2) + lastChar`.\n- Otherwise print original word.',
    link_verified: true,
    ease_factor: 2.9,
    interval_days: 21,
    repetitions: 6, // Mastered!
    next_review_date: addDaysToDate(today, 12),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'p-8',
    title: 'Reverse a Linked List',
    url: 'https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1',
    platform: 'gfg',
    difficulty: 'easy',
    tags: ['Linked List'],
    notes: '### Approach:\n- 3 pointers: `prev = null`, `curr = head`, `next = null`.\n- Loop: `next = curr.next; curr.next = prev; prev = curr; curr = next;`.\n- Return `prev`.',
    link_verified: true,
    ease_factor: 2.7,
    interval_days: 18,
    repetitions: 5, // Mastered!
    next_review_date: addDaysToDate(today, 8),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'p-9',
    title: 'Course Schedule',
    url: 'https://leetcode.com/problems/course-schedule/',
    platform: 'leetcode',
    difficulty: 'medium',
    tags: ['Graph', 'DFS/BFS', 'Topological Sort'],
    notes: '### Topological Sort:\n- Build adjacency list and calculate in-degrees.\n- Enqueue all nodes with `in_degree == 0`.\n- If processed count == numCourses, valid schedule exists.',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 7,
    repetitions: 3,
    next_review_date: addDaysToDate(today, 3),
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'p-10',
    title: 'Theatre Square',
    url: 'https://codeforces.com/problemset/problem/1/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Math'],
    notes: '### Formula:\n- Flagstones along n: `ceil(n / a) = ((n + a - 1) / a)`\n- Flagstones along m: `ceil(m / a) = ((m + a - 1) / a)`\n- Result: product of both. Use `long long` in C++ / BigInt to avoid integer overflow!',
    link_verified: true,
    ease_factor: 2.6,
    interval_days: 10,
    repetitions: 4,
    next_review_date: addDaysToDate(today, 4),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'p-11',
    title: 'Subarray with Given Sum',
    url: 'https://www.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Two Pointers', 'Arrays'],
    notes: '### Two pointers:\n- Expand `right` until `sum >= target`.\n- Contract `left` while `sum > target`.\n- Beware of 1-based indexing in GFG answers.',
    link_verified: true,
    ease_factor: 2.45,
    interval_days: 6,
    repetitions: 3,
    next_review_date: addDaysToDate(today, 2),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'p-12',
    title: 'Binary Tree Maximum Path Sum',
    url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    platform: 'leetcode',
    difficulty: 'hard',
    tags: ['Trees', 'DFS/BFS', 'Dynamic Programming'],
    notes: '### Recursion with global max:\n- Each node computes max contribution to its parent: `node.val + max(0, max(leftGain, rightGain))`.\n- Local path through node: `node.val + max(0, leftGain) + max(0, rightGain)` updates `maxSum`.',
    link_verified: true,
    ease_factor: 2.3,
    interval_days: 5,
    repetitions: 2,
    next_review_date: addDaysToDate(today, 1),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'p-13',
    title: 'Team',
    url: 'https://codeforces.com/problemset/problem/231/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Greedy'],
    notes: 'Count rows where sum of certainty flags `a + b + c >= 2`.',
    link_verified: true,
    ease_factor: 2.9,
    interval_days: 30,
    repetitions: 6, // Mastered
    next_review_date: addDaysToDate(today, 20),
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'p-14',
    title: 'Word Boggle',
    url: 'https://www.geeksforgeeks.org/problems/word-boggle4143/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Backtracking', 'Trie'],
    notes: 'Insert dictionary into Trie. Run 8-directional DFS from each cell. Prune branches if Trie prefix does not exist.',
    link_verified: true,
    ease_factor: 2.35,
    interval_days: 5,
    repetitions: 2,
    next_review_date: addDaysToDate(today, 2),
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'p-15',
    title: 'Next Round',
    url: 'https://codeforces.com/problemset/problem/158/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Arrays'],
    notes: 'Participant advances if `score >= k-th participant score` AND `score > 0`.',
    link_verified: true,
    ease_factor: 2.7,
    interval_days: 25,
    repetitions: 5,
    next_review_date: addDaysToDate(today, 15),
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
];
