import { Problem } from '../types';
import { formatDate, addDaysToDate } from './spacedRepetition';

export const PRESET_TAGS = [
  'Arrays',
  'Strings',
  'Two Pointers',
  'Sliding Window',
  'Hashing',
  'Linked List',
  'Stack',
  'Queue',
  'Binary Search',
  'Sorting',
  'Recursion',
  'Backtracking',
  'Trees',
  'BST',
  'Heap',
  'Graph',
  'DFS/BFS',
  'Dynamic Programming',
  'Greedy',
  'Bit Manipulation',
  'Math',
  'Trie',
  'Union-Find',
];

const today = formatDate();
const yesterday = addDaysToDate(today, -1);
const twoDaysAgo = addDaysToDate(today, -2);
const threeDaysAgo = addDaysToDate(today, -3);

export const ESSENTIAL_PROBLEMS: Omit<Problem, 'id' | 'created_at'>[] = [
  {
    title: 'Two Sum',
    url: 'https://leetcode.com/problems/two-sum/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Arrays', 'Hashing'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 0,
    next_review_date: today,
  },
  {
    title: 'Reverse Linked List',
    url: 'https://leetcode.com/problems/reverse-linked-list/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Linked List', 'Recursion'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 0,
    next_review_date: today,
  },
  {
    title: 'Valid Parentheses',
    url: 'https://leetcode.com/problems/valid-parentheses/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Stack', 'Strings'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 0,
    next_review_date: today,
  },
  {
    title: 'Binary Search',
    url: 'https://leetcode.com/problems/binary-search/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Binary Search', 'Arrays'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 0,
    next_review_date: today,
  },
  {
    title: 'Maximum Subarray',
    url: 'https://leetcode.com/problems/maximum-subarray/',
    platform: 'leetcode',
    difficulty: 'medium',
    tags: ['Arrays', 'Dynamic Programming'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 0,
    next_review_date: today,
  },
];

export const SAMPLE_PROBLEMS: Problem[] = [
  // Overdue problems (for revision queue urgent attention)
  {
    id: 'p-1',
    title: 'Two Sum',
    url: 'https://leetcode.com/problems/two-sum/',
    platform: 'leetcode',
    difficulty: 'easy',
    tags: ['Arrays', 'Hashing'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 1,
    repetitions: 1,
    next_review_date: yesterday, // Overdue
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'p-2',
    title: 'Detect Cycle in a Directed Graph',
    url: 'https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Graph', 'DFS/BFS'],
    notes: '',
    link_verified: true,
    ease_factor: 2.35,
    interval_days: 2,
    repetitions: 2,
    next_review_date: twoDaysAgo, // Overdue
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },

  // Due today problems
  {
    id: 'p-3',
    title: 'Trapping Rain Water',
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    platform: 'leetcode',
    difficulty: 'hard',
    tags: ['Two Pointers', 'Stack', 'Arrays'],
    notes: '',
    link_verified: true,
    ease_factor: 2.4,
    interval_days: 3,
    repetitions: 2,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'p-4',
    title: 'Watermelon',
    url: 'https://codeforces.com/problemset/problem/4/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Math', 'Greedy'],
    notes: '',
    link_verified: true,
    ease_factor: 2.8,
    interval_days: 5,
    repetitions: 3,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'p-5',
    title: 'Kadane\'s Algorithm',
    url: 'https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Arrays', 'Dynamic Programming'],
    notes: '',
    link_verified: true,
    ease_factor: 2.65,
    interval_days: 4,
    repetitions: 3,
    next_review_date: today, // Due today
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },

  // Future review / Mastered problems
  {
    id: 'p-6',
    title: 'LRU Cache',
    url: 'https://leetcode.com/problems/lru-cache/',
    platform: 'leetcode',
    difficulty: 'medium',
    tags: ['Linked List', 'Hashing'],
    notes: '',
    link_verified: true,
    ease_factor: 2.8,
    interval_days: 14,
    repetitions: 5, // Mastered!
    next_review_date: addDaysToDate(today, 6),
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'p-7',
    title: 'Way Too Long Words',
    url: 'https://codeforces.com/problemset/problem/71/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Strings'],
    notes: '',
    link_verified: true,
    ease_factor: 2.9,
    interval_days: 21,
    repetitions: 6, // Mastered!
    next_review_date: addDaysToDate(today, 12),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'p-8',
    title: 'Reverse a Linked List',
    url: 'https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1',
    platform: 'gfg',
    difficulty: 'easy',
    tags: ['Linked List'],
    notes: '',
    link_verified: true,
    ease_factor: 2.7,
    interval_days: 18,
    repetitions: 5, // Mastered!
    next_review_date: addDaysToDate(today, 8),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'p-9',
    title: 'Course Schedule',
    url: 'https://leetcode.com/problems/course-schedule/',
    platform: 'leetcode',
    difficulty: 'medium',
    tags: ['Graph', 'DFS/BFS', 'Topological Sort'],
    notes: '',
    link_verified: true,
    ease_factor: 2.5,
    interval_days: 7,
    repetitions: 3,
    next_review_date: addDaysToDate(today, 3),
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'p-10',
    title: 'Theatre Square',
    url: 'https://codeforces.com/problemset/problem/1/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Math'],
    notes: '',
    link_verified: true,
    ease_factor: 2.6,
    interval_days: 10,
    repetitions: 4,
    next_review_date: addDaysToDate(today, 4),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'p-11',
    title: 'Subarray with Given Sum',
    url: 'https://www.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Two Pointers', 'Arrays'],
    notes: '',
    link_verified: true,
    ease_factor: 2.45,
    interval_days: 6,
    repetitions: 3,
    next_review_date: addDaysToDate(today, 2),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'p-12',
    title: 'Binary Tree Maximum Path Sum',
    url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    platform: 'leetcode',
    difficulty: 'hard',
    tags: ['Trees', 'DFS/BFS', 'Dynamic Programming'],
    notes: '',
    link_verified: true,
    ease_factor: 2.3,
    interval_days: 5,
    repetitions: 2,
    next_review_date: addDaysToDate(today, 1),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'p-13',
    title: 'Team',
    url: 'https://codeforces.com/problemset/problem/231/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Greedy'],
    notes: '',
    link_verified: true,
    ease_factor: 2.9,
    interval_days: 30,
    repetitions: 6, // Mastered
    next_review_date: addDaysToDate(today, 20),
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'p-14',
    title: 'Word Boggle',
    url: 'https://www.geeksforgeeks.org/problems/word-boggle4143/1',
    platform: 'gfg',
    difficulty: 'medium',
    tags: ['Backtracking', 'Trie'],
    notes: '',
    link_verified: true,
    ease_factor: 2.35,
    interval_days: 5,
    repetitions: 2,
    next_review_date: addDaysToDate(today, 2),
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'p-15',
    title: 'Next Round',
    url: 'https://codeforces.com/problemset/problem/158/A',
    platform: 'codeforces',
    difficulty: 'easy',
    tags: ['Arrays'],
    notes: '',
    link_verified: true,
    ease_factor: 2.7,
    interval_days: 25,
    repetitions: 5,
    next_review_date: addDaysToDate(today, 15),
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
];
